sudo: false

language: php

php:
  - 7.2
  - 7.3

env:
  - MAKE_FILE=drupal-8.6.x.make.yml
  - MAKE_FILE=drupal-8.7.x.make.yml
  - MAKE_FILE=drupal-8.8.x.make.yml

matrix:
  allow_failures:
    # This should fail because of https://www.drupal.org/project/multiversion/issues/3090566.
    - env: MAKE_FILE=drupal-8.8.x.make.yml
  fast_finish: true

services:
  - mysql

addons:
  apt:
    packages:
      - nginx

cache:
  directories:
  - $HOME/.drush/cache/download

before_install:
  - composer self-update
  - cp $TRAVIS_BUILD_DIR/.travis/php.ini ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/
  - cp $TRAVIS_BUILD_DIR/.travis/php-fpm.conf ~/.phpenv/versions/$(phpenv version-name)/etc/
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - nginx -c $TRAVIS_BUILD_DIR/.travis/nginx.conf
  - wget -P ~/ https://github.com/drush-ops/drush/releases/download/8.2.3/drush.phar && chmod +x ~/drush.phar
  - php ~/drush.phar make $TRAVIS_BUILD_DIR/.travis/$MAKE_FILE $HOME/www
  - php ~/drush.phar --root=$HOME/www --yes site-install --db-url=mysql://root:@127.0.0.1/drupal testing
  - if [ $MAKE_FILE != drupal-8.8.x.make.yml ]; then composer --working-dir=$HOME/www run-script drupal-phpunit-upgrade; fi

install:
  - ln -s $TRAVIS_BUILD_DIR ~/www/modules/replication

script:
  - cd ~/www && php ./core/scripts/run-tests.sh --suppress-deprecations --verbose --keep-results --color --concurrency 4 --php `which php` --sqlite /tmp/test.sqlite --url http://localhost:8080 --module replication

after_script:
  - find ~/www/sites/simpletest/browser_output -type f -exec cat {} \;
  - cat /tmp/error.log
